language: python
python:
    - "2.7"
env:
    - SUPERVISOR_PYTHON_VERSION=2.7
install:
    - pip install -e .
    - pip install -e .[tests]
    - ./install_supervisor.sh
script:
    - pre-commit run --all
    - python setup.py test
sudo: false
deploy:
  provider: pypi
  user:
    secure: "k8cQzjioeGdRV7U46QemYrJjWvgvqwIdOgS+qJN6RV03GtD9aXIfLRECgUeuja6zu9by1z/x/0wRq2h1+41PannYkxwXtn2ivMWzqGc+zmqiPmuM2zMX/z0rmV8pF3Gq20afUkFEA6iDVjtd/x4ejzOOWgoMq3gVSZ+zhFBRyycK37VaOPvSqBqZYLM/jaZKgQJEFBY8qOf8TIgkGYyj+o/s4yFoV+AfYzs/YwvIeGs9Bhoi36J9/Gg888WmGS05olMAem5YlU5BrOjJs4RtI76O4FXT+kv1g5GTBKL1Q97x7MMg+0MAZgt8IBEZx91A9f2rtGvy6+8IMqW001HfaKf5ppRzpjaFfiuSAv9LpkqHr3en/vqljK6PGpxKFPTSXe/NYeKdJRXGWhqJ//8ma82X8RFbDyje/raQx9nKQ5+CtNpWlMRlhmIZQOvf6OhytgCOWfa/EOfOuH05I5tx6yL0tIlcr+ccVJ8jIL75L5IJSU8k0Q7pi+WQWAJymIOWeiiWjI5d3bHdZ0MX2KXvznxcwLpBE7TgT8iy89LmC4Xp7x1bY1ch3XwhUSEog8Qe2voY9ApQI9anxlSrNaFZoAAYnbn9dDHCbkV8tJjm7BO19ekuykMubIVmE4QJ1W53/MZJHgl4CgbR9iuYaInKvTR5nPKJ+R4qq/Nc9o9qbto="
  password:
    secure: "XTQjLtVHZO+XX74si9nUf8z1EW/XKBPquwRA1xipTlaktfhQwz85fVdadsx0EPpOjorhCnZMZJ73hiYE9y2LfHHL4ECp+0pUGzXJdGCRZWKI7g9Kcv8ICu0SmjgUDwyHhW5Ft36Ye4IHr1HTb80BYjHVs/pkpQF7Wwm4TexK/APT1IT4E5LIPaYGnukEHIGn3esJdd1ypKk0SztS9ka5HGNlh+yM5VhAsH0qJSFd7hBO9NRHj7ygZXHRP6qgTuToX8VKhpD9fqisL0imDijEvTHWLktlkvJLI6i3X5le9g2CZJuhpf2XVPPZ40KURb88uZRNlkjPWsS8GTmFlwgH5fqimTl/GLkv1+zlDipCA/Z4oKh8nCgW6sfX2a3qYuHKUpMfcaTPFJQnGbuMd+9BxY2Js86+phgPySXbJut3AfSz1aHr/H48nWHvhNzUfeFEHoeTEmZmEarUKdMY3qsvpuoEaCrJ2jPVVeIyuufkjssOy2Dvongm8dcP8hj6MKcUhP9bEjRHXzOEhiD6Y1WRENDRN2o8mmwfQy6TSAZ/djnXG1wtl7GadJBtDd6emT2ot2sL4Q7bSx/oR01A+6j7VRjHHXFQDBvei+RQrPTCqvL68BtKkokS863CAk8iIJuX+LWVLoygz3ryuOk6BIiEkuZla/TwQhRnV6R5PoD2R6M="
  on:
    tags: true
